name: We Oui
favicon: null
layout_spectrum: 0.5319002023898065
typography_spectrum: 0.47452800325118005
title: weoui.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.012479259399697185
  lightness: 0.9314093322027475
  saturation: 0.4114257241599262
  rhythmicContrast: 0.18723994633182883
purpose: []
